version: '3.7'

services:

  elasticsearch:

    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    environment:
      # - "ES_JAVA_OPTS= -Xms256m -Xmx256m"
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    volumes:
      - esdata:/usr/share/elasticsearch/data  # persist data
      # - "./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
    networks:
      - es-net
    ports:
      - 9200:9200
      - 9300:9300

  kibana:

    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.1.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    #volumes:
    #  - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro

    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

volumes:
  esdata:
    driver: local  

networks:
  es-net:
    driver: bridge
